// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Ticketing.Infrastructure.Persistence;

#nullable disable

namespace Ticketing.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    partial class TicketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at_utc");

                    b.Property<int>("TotalCapacity")
                        .HasColumnType("integer")
                        .HasColumnName("total_capacity");

                    b.Property<uint>("xmin")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_events");

                    b.ToTable("events", null, t =>
                        {
                            t.HasCheckConstraint("ck_events_capacity_positive", "total_capacity > 0");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Events.PricingTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Allocation")
                        .HasColumnType("integer")
                        .HasColumnName("allocation");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<int>("Remaining")
                        .HasColumnType("integer")
                        .HasColumnName("remaining");

                    b.HasKey("Id")
                        .HasName("pk_pricing_tiers");

                    b.HasAlternateKey("Id", "EventId")
                        .HasName("ak_pricing_tiers_id_event_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_pricing_tiers_event_id");

                    b.ToTable("pricing_tiers", null, t =>
                        {
                            t.HasCheckConstraint("ck_pricing_tiers_allocation_positive", "allocation > 0");

                            t.HasCheckConstraint("ck_pricing_tiers_price_non_negative", "price >= 0");

                            t.HasCheckConstraint("ck_pricing_tiers_remaining_non_negative", "remaining >= 0");

                            t.HasCheckConstraint("ck_pricing_tiers_remaining_within_allocation", "remaining <= allocation");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("idempotency_key");

                    b.Property<DateTimeOffset>("PlacedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("placed_at_utc");

                    b.Property<Guid>("PricingTierId")
                        .HasColumnType("uuid")
                        .HasColumnName("pricing_tier_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("Total")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_orders_event_id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_orders_idempotency_key");

                    b.HasIndex("PricingTierId", "EventId")
                        .HasDatabaseName("ix_orders_pricing_tier_id_event_id");

                    b.ToTable("orders", null, t =>
                        {
                            t.HasCheckConstraint("ck_orders_quantity_positive", "quantity > 0");

                            t.HasCheckConstraint("ck_orders_total_matches_unit_price", "total = unit_price * quantity");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("IssuedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at_utc");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_tickets_order_id");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Ticketing.Domain.Events.Event", b =>
                {
                    b.OwnsOne("Ticketing.Domain.Events.Venue", "Venue", b1 =>
                        {
                            b1.Property<Guid>("EventId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("venue_name");

                            b1.Property<string>("TimeZoneId")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("venue_time_zone_id");

                            b1.HasKey("EventId");

                            b1.ToTable("events");

                            b1.WithOwner()
                                .HasForeignKey("EventId")
                                .HasConstraintName("fk_events_events_id");
                        });

                    b.Navigation("Venue")
                        .IsRequired();
                });

            modelBuilder.Entity("Ticketing.Domain.Events.PricingTier", b =>
                {
                    b.HasOne("Ticketing.Domain.Events.Event", null)
                        .WithMany("Tiers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pricing_tiers_events_event_id");
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Order", b =>
                {
                    b.HasOne("Ticketing.Domain.Events.PricingTier", null)
                        .WithMany()
                        .HasForeignKey("PricingTierId", "EventId")
                        .HasPrincipalKey("Id", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_pricing_tiers_pricing_tier_id_event_id");
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Ticket", b =>
                {
                    b.HasOne("Ticketing.Domain.Orders.Order", null)
                        .WithMany("Tickets")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_orders_order_id");
                });

            modelBuilder.Entity("Ticketing.Domain.Events.Event", b =>
                {
                    b.Navigation("Tiers");
                });

            modelBuilder.Entity("Ticketing.Domain.Orders.Order", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
