name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - run: dotnet restore
      - run: dotnet build --no-restore --configuration Release
      - run: dotnet format --verify-no-changes
      - run: dotnet test --no-build --configuration Release
